language: node_js
node_js:
    - "6"
script:
    - |
        cat <<EOF > src/secrets.js
        export const clientId = 'placeholder';
        export const clientSecret = 'placeholder';
        export const LISH_ROOT = 'wss://lish.alpha.linode.com';
        EOF
    - npm test
    - cat ./coverage/lcov.info | node ./bin/styleguideTestFilter.js | ./node_modules/.bin/coveralls
    - npm run lint
