sudo: required
language: node_js
node_js:
  - "8.4.0"
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
cache:
  yarn: true
install:
    - yarn
    - (cd docs && yarn)
    - (cd components && yarn)
script:
    - set -e
    - |
        cat <<EOF > src/secrets.js
        export const clientId = 'placeholder';
        export const clientSecret = 'placeholder';
        EOF
    - |
      if [[ $(git diff HEAD^ $(git rev-parse --abbrev-ref HEAD) --name-only | grep -v scss) ]]; then
        yarn run lint
        (cd docs && yarn run lint && yarn run prebuild)
        (cd components && yarn run lint)
        yarn test -- --coverage --maxWorkers=2
        cat ./coverage/lcov.info | node ./bin/styleguideTestFilter.js | ./node_modules/.bin/coveralls
      fi
